# Grid
GRID_SIZE = 10

# Economy
STARTING_BUDGET = 2000
STARTING_POPULATION = 0
REVENUE_RESIDENTIAL = 10
REVENUE_COMMERCIAL = 20
REVENUE_INDUSTRIAL = 35
EXPENSE_ROAD = 3
EXPENSE_ZONE = 1

# Building costs
COST_ROAD = 50
COST_RESIDENTIAL = 100
COST_COMMERCIAL = 150
COST_INDUSTRIAL = 200
COST_CLEAR = 25

# Population
POP_PER_RESIDENTIAL = 50
POP_CHANGE_RATE = 0.20
BANKRUPTCY_POP_PENALTY = 0.05
DEMAND_SURGE_DIVISOR = 1.5

# Pollution
POLLUTION_EMISSION = 0.3
POLLUTION_SPREAD_FACTOR = 0.15
POLLUTION_DECAY = 0.05

# Livability
LIVABILITY_BASE = 1.0
POLLUTION_PENALTY = 0.5
COMMERCIAL_BONUS = 0.3
CONGESTION_WEIGHT = 0.2

# Simulation
TURNS = 50

# Scoring
THEORETICAL_MAX_POP = 4000
EFFICIENCY_SCALING_FACTOR = 100 / (POP_PER_RESIDENTIAL * GRID_SIZE)
MAX_ACTIONS_PER_TURN = 50
LOG_RAW_RESPONSE_MAX_CHARS = 500

# Disaster probabilities per tick
DISASTER_RECESSION_PROB = 0.04
DISASTER_DEMAND_SURGE_PROB = 0.03
DISASTER_INFRA_FAIL_PROB = 0.03
DISASTER_POLLUTION_PROB = 0.03
DISASTER_RECESSION_DURATION = 3
DISASTER_DEMAND_SURGE_DURATION = 3
DISASTER_INFRA_FAIL_DURATION = 2

# Ollama
OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_TIMEOUT = 90
DEFAULT_MODEL = "llama3:8b"
